# Multi_variable Linear Regression

In [4]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import pandas as pd

In [5]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]


In [12]:
df_x1 = pd.DataFrame(x1_data, columns = ['X1'])
df_x2 = pd.DataFrame(x2_data, columns = ['X2'])
df_x3 = pd.DataFrame(x3_data, columns = ['X3'])
df_y = pd.DataFrame(y_data, columns = ['Y'])
df = pd.concat([df_x1, df_x2, df_x3, df_y], axis=1)
df

X1    X2     X3      Y
0  73.0  80.0   75.0  152.0
1  93.0  88.0   93.0  185.0
2  89.0  91.0   90.0  180.0
3  96.0  98.0  100.0  196.0
4  73.0  66.0   70.0  142.0

H(x1, x2, x3) = x1w1 + x2w2 + x3w3 + bias

In [13]:
#placeholders for a tensor that will be a always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [14]:
#cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - y))

#Minimize. Need a very small Learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

#Launch the graph in a session
sess = tf.Session()

#Initializes global variables in the graph

sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    if step % 100 == 0:
        print(step, "Cost : ", cost_val, "\n Prediction: \n", hy_val)
    

0 Cost :  23552.15 
 Prediction: 
 [12.756904 22.513023 18.3861   22.057468 17.119898]
100 Cost :  2.6858063 
 Prediction: 
 [148.96268 186.14319 179.65527 197.6647  141.91786]
200 Cost :  2.6257203 
 Prediction: 
 [149.00377 186.11557 179.6686  197.66853 141.88655]
300 Cost :  2.5684438 
 Prediction: 
 [149.04385 186.08868 179.68163 197.67216 141.85617]
400 Cost :  2.51384 
 Prediction: 
 [149.08292 186.06248 179.69434 197.67555 141.82668]
500 Cost :  2.4617772 
 Prediction: 
 [149.12102 186.03697 179.70677 197.67877 141.79807]
600 Cost :  2.4121206 
 Prediction: 
 [149.15816 186.01208 179.71889 197.6818  141.7703 ]
700 Cost :  2.3647444 
 Prediction: 
 [149.19435 185.98784 179.7307  197.68459 141.74333]
800 Cost :  2.3195162 
 Prediction: 
 [149.22966 185.96423 179.74226 197.6872  141.71716]
900 Cost :  2.2763522 
 Prediction: 
 [149.26408 185.94121 179.75356 197.68965 141.69179]
1000 Cost :  2.2351198 
 Prediction: 
 [149.29767 185.91878 179.76457 197.69194 141.66719]
1100 Cost :  2

In [18]:
pr_y = pd.Series(hy_val, name = 'Prediction')
df_pr = df.join(pr_y)
df_pr

X1    X2     X3      Y  Prediction
0  73.0  80.0   75.0  152.0  149.590927
1  93.0  88.0   93.0  185.0  185.723404
2  89.0  91.0   90.0  180.0  179.861664
3  96.0  98.0  100.0  196.0  197.705811
4  73.0  66.0   70.0  142.0  141.458374

***
Prediction is that It is estimated from Y using linear regression model and Y is actual value.<br>
It shows that Predictions are reverted Ys when the model is executed for 2000 times.<br>
So It will be closer Y and Prediction if the model is attempted over 2000.
***

In [19]:
#using matrix 
X_data = [[73., 80., 75.],[93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
Y_data = [[152.], [185.],[180.], [196.], [142.]]

#placeholders for a tensor that will be a always fed.
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight1')
B = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + B

#cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

#Minimize. Need a very small Learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

#Launch the graph in a session
sess = tf.Session()

#Initializes global variables in the graph

sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X:X_data, Y:Y_data})
    if step % 100 == 0:
        print(step, "Cost : ", cost_val, "\n Prediction: \n", hy_val)
    

0 Cost :  113556.625 
 Prediction: 
 [[-143.80533]
 [-177.29562]
 [-172.552  ]
 [-188.22011]
 [-135.68011]]
100 Cost :  6.785334 
 Prediction: 
 [[155.08862]
 [182.14305]
 [181.51009]
 [197.35468]
 [138.52014]]
200 Cost :  6.4368286 
 Prediction: 
 [[154.9905 ]
 [182.21045]
 [181.48018]
 [197.33183]
 [138.6096 ]]
300 Cost :  6.106717 
 Prediction: 
 [[154.895  ]
 [182.27605]
 [181.45108]
 [197.30962]
 [138.69669]]
400 Cost :  5.7939577 
 Prediction: 
 [[154.80205]
 [182.33987]
 [181.42274]
 [197.28793]
 [138.78145]]
500 Cost :  5.4977164 
 Prediction: 
 [[154.71161]
 [182.402  ]
 [181.39517]
 [197.26682]
 [138.86395]]
600 Cost :  5.2171254 
 Prediction: 
 [[154.62361]
 [182.46243]
 [181.36838]
 [197.24625]
 [138.94427]]
700 Cost :  4.951315 
 Prediction: 
 [[154.53798]
 [182.52126]
 [181.34229]
 [197.22621]
 [139.02246]]
800 Cost :  4.699496 
 Prediction: 
 [[154.45465]
 [182.5785 ]
 [181.3169 ]
 [197.20667]
 [139.09857]]
900 Cost :  4.460943 
 Prediction: 
 [[154.37355]
 [182.63422]
 